spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog.xml
    default-schema: public
  application:
    name: game-shop-api
  datasource:
    url: jdbc:postgresql://localhost:5432/game-shop-api
    username: ideal
    password: 111
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080
  # netstat -ano | findstr :8080 - для проверки занятости порта
  # taskkill /PID ..... /F - для удаления задачи которая занимает порт

logging:
  level:
    liquibase: DEBUG
    root: INFO
  org:
    springframework:
      security: DEBUG
      web: DEBUG